ValleyBell/libvgm

audemutest.c, audiotest.c, vgmtest.c
Fixes compilation errors with DEBUG = 1 such as 
```
audiotest.c:227: undefined reference to `_CrtDumpMemoryLeaks'
```
on non-Windows operating systems.
=> call _CrtDumpMemoryLeaks() only under Windows

CMakeLists.txt, cmake/sanitizers/FindASan.cmake, cmake/sanitizers/FindMSan.cmake, cmake/sanitizers/FindSanitizers.cmake, cmake/sanitizers/FindTSan.cmake, cmake/sanitizers/FindUBSan.cmake, cmake/sanitizers/asan-wrapper, cmake/sanitizers/sanitize-helpers.cmake
This PR adds sanitizers to cmake.
They can be used by setting their respective variable when calling cmake.
For example
```
cmake .. -DCMAKE_BUILD_TYPE=Debug -DSANITIZE_ADDRESS=1
```
or
```
CXX=clang++ CC=clang cmake .. -DCMAKE_BUILD_TYPE=Debug -DSANITIZE_UNDEFINED=1
```
I have only tested this on Linux, but it should not affect unsupported platforms, as the sanitizers are off by default.
=> Add sanitizers to cmake

player.cpp, player/droplayer.cpp, player/droplayer.hpp, player/playerbase.hpp, player/s98player.cpp, player/s98player.hpp, player/vgmplayer.cpp, player/vgmplayer.hpp
In replacement of PR #17, following suggestions of @superctr and @jprjr
It provides access to tags as an array of string pairs with a NULL terminator.
**Tag specification**
- [Vorbis](https://sno.phy.queensu.ca/~phil/exiftool/TagNames/Vorbis.html) as suggested: "TITLE", "ARTIST", "DATE", "ENCODED_BY", "COMMENT", "GENRE", "COPYRIGHT"
- `GAME` and `SYSTEM` tags which are not part of the specification
- for multi-language tags I have used a notation such as "TITLE-JPN"
I imitated an ID3 feature documented [here](https://sno.phy.queensu.ca/~phil/exiftool/TagNames/ID3.html) which reads:
`ID3v2 tags which support multiple languages (eg. Comment and Lyrics) are extracted by specifying the tag name, followed by a dash ('-'), then a 3-character ISO 639-2 language code (eg. "Comment-spa").`
I have …
=> Get track information as array of Vorbis-style tags

player/s98player.cpp
It fixes this error:
`s98player.cpp:310:54: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]`
=> fix a compilation error on gcc

emu/cores/emu2413.c
On clang on OSX, emu2413 was generating an undefined symbol for `INIT_DEVINT` since `INLINE` didn't include `static`
This removes it since a few lines below, `#include "../snddef.h"` winds up bringing in the shared `INLINE` definition.
=> emu2413: remove custom INLINE def (brought in via snddef include)

emu/EmuStructs.h, emu/cores/emu2413.c
Looks like you were right about #32 - gcc on linux complained about `static static`
This proposed fix is to have `INIT_DEVINF` use its own `INLINE` macro so it's always `static inline`.
=> Really fix inline

CMakeLists.txt
An issue I ran into on Linux was compiling `emu2413` - it looks like stdint.h doesn't get included and types like `uint8_t` never get defined.
I updated the `CMakeLists` to check for stdint.h and set the define that way.
=> CMakeLists: check for stdint, define HAVE_STDINT

CMakeLists.txt, audio/CMakeLists.txt, emu/CMakeLists.txt, player/CMakeLists.txt, utils/CMakeLists.txt
By default on linux/unix, doing a `make install` after building creates a directory layout like:
`/usr/local/include/utils/DataLoader.h`
This just places everything into a `vgm` directory, like
`/usr/local/include/vgm/utils/DataLoader.h`
That way it's obvious where/what these headers are for, just based on the filename. Plus it makes them more inline with the library naming (`vgm-utils` => `vgm/utils`, `vgm-player` => `vgm/player`, etc).
=> install target: place headers into a "vgm" directory

audio/CMakeLists.txt, emu/CMakeLists.txt, player/CMakeLists.txt, utils/CMakeLists.txt
hello! i noticed that when i attempt to run cmake in any of the project subdirectories (emu, player, audio, utils), the following error occurs:
```
CMake Error at CMakeLists.txt:2 (project):
VERSION not allowed unless CMP0048 is set to NEW
```
it appears to have started with [this recent commit](https://github.com/ValleyBell/libvgm/commit/22b4789924840da6c24c16d5054f16a55649cc1c), which added the VERSION variables to the respective CMakeLists. 
setting the [CMP0048 policy](https://cmake.org/cmake/help/v3.0/policy/CMP0048.html) as per the error message appears to have fixed the problem.
=> fix VERSION/CMP0048 errors in CMakeLists

player/s98player.cpp, player/vgmplayer.cpp
Currently it looks like RefreshMuting will set the same muting mask to the pair of linked devices. I think this change was what was intended.
=> Index through the PLR_MUTE_OPTS chnMute array for linked device.

CMakeLists.txt, audio/CMakeLists.txt
This solves the issues with the previous PR #46.
It seems like the static libao library has linking errors on my MinGW install, so I disabled it by default. I think it should be no issue to do this since there are already multiple other audio drivers usable for Windows.
=> Add option to build with static libraries for MSYS/MinGW

utils/StrUtils-CPConv_IConv.c
Have not had the opportunity to test this on OSX, but on POSIX systems the strcasecmp and strncasecmp should be used (strnicmp doesn't exist on my Linux system)
=> strutils: use strcasecmp/strncasecmp on non-windows

emu/cores/ym2612.c
Noticed these were exposed as global symbols, but they're not used anywhere else
=> ym2612: make SLOT_SET, CHANNEL_SET, and YM_SET local

player.cpp
Oops, file handle leaks due to no fclose.
=> player: Close file handles instead of leaking them

.github/workflows/GHA.yml
A Visual Studio build is unfortunately a bit more complicated.
The repo currently ships with zlib and iconv builds done using MSVC 6 or 2010.  
There was a ABI break between VC 2013 and 2015 that prevents all of the static libraries from working with VC2015 and higher.  
DLLs (e.g. zdll.lib) work fine though.
There is currently no MSVC 64-bit build, because all included 64-bit libraries are static builds, which of course don't work with VC2019.
=> add MSVC CI jobs

emu/CMakeLists.txt
The new header hasn't been added to the installed headers of the emu CMakeLists.txt. Without this, vgmplay-libvgm build errors out:
```
In file included from /build/source/playctrl.cpp:35:
/nix/store/wlaysm4d7zym0z9alr98q5mxj1zp6i4z-libvgm-unstable-2021-11-26-dev/include/vgm/player/droplayer.hpp:10:10: fatal error: ../emu/logging.h: No such file or directory
10 | #include "../emu/logging.h"
|          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /build/source/mediainfo.cpp:14:
/nix/store/wlaysm4d7zym0z9alr98q5mxj1zp6i4z-libvgm-unstable-2021-11-26-dev/include/vgm/player/droplayer.hpp:10:10: fatal error: ../emu/logging.h: No such file or directory
10 | #include "../emu/logging.h"
|          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** …
```
=> Fix missing logging header installation

player.cpp, vgm2wav.cpp
`DataLoader_Deinit` now calls `DataLoader_Reset`, which calls `DataLoader_CancelLoading`. So calling `DataLoader_CancelLoading` before `DataLoader_Deinit` is redundant. So remove the call to `DataLoader_CancelLoading` in the example apps, to simplify the code.
(Hopefully this change is correct.)
=> Don't call DataLoader_CancelLoading before DataLoader_Deinit in examples

player/vgmplayer.cpp, player/vgmplayer.hpp
Fixes several old dumps. Hopefully works properly for YM2151 dumps as well.
Fixes #88
=> VGMPlayer: scan v1.00/v1.01 files for FM clock used

utils/OSThread_POSIX.c
> ```
> utils/OSThread_POSIX.c:88:9: warning: incompatible pointer to integer conversion returning 'const pthread_t' (aka 'struct _opaque_pthread_t *const') from a function with result type 'UINT64' (aka 'unsigned long long') [-Wint-conversion]
> ```
`pthread_t` on macOS is more than just an unsigned long int typedef, properly getting a numerical id requires the use of a non-portable function.
=> Fix OSThread_GetID on Darwin

emu/cores/ymf278b.c
In afded2e the position increment and loop check was changed to reproduce the
noise effect in Omega’s Lizard Star track, however in the process this also
changed which samples were read in to interpolate between.
The interpolation should always be between two consecutive samples, however
after the prior change they would be several samples apart when the increment
is greater than 1. This generates an incorrectly interpolated sample value.
The issue is fixed by retrieving the two samples directly in the location where
they are interpolated, and the double buffer (sample1, sample2) is removed.
See https://github.com/openMSX/openMSX/issues/1400
=> YMF278B: Fix aliasing in high pitched notes.

emu/cores/ymf278b.c
I verified on real OPL4 that changing wave during key on indeed retriggers the EG, and doing so during key off does not. The EG state is unaffected other than the new wave table parameters being applied to it. The sample position does get reset though, so it plays from the beginning.
See https://github.com/openMSX/openMSX/pull/1420 for test case.
=> YMF278: Restart sample position when wave changes during release.

utils/OSThread_POSIX.c
Same warning as with Darwin (#95), same spiel of Haiku having a helper function for getting the numeric id of a pthread.
=> Fix OSThread_GetID on Haiku

emu/Resampler.c, player/s98player.cpp
1. Make sure `S98Player::_fileHdr` is zero-initialized by the constructor.
2. Handle resampling of blocks larger than the initial sample buffer size by allocating a larger buffer when necessary. Fixes #12.
=> Fix some memory errors

player/playera.cpp, vgm2wav.cpp
Fixes #108 , also obsoletes #109 
Replacing the direct assigned-to-pointer-casts with memcpy calls avoids potential undefined behavior (like if the sample buffer wasn't allocated on the correct byte boundary). On systems where the alignment is a non-issue, compilers should replace memcpy calls with the equivalent of `*(INT16*)buffer = (INT16)value;` etc.
=> Fix alignment issues and portable 24bps packing

emu/cores/mikey.c
Changed algorithm to be more fit to higher sampling rate (up to 1M sps)
=> Refactoring and optimizing for 1M sps playback.

player/vgmplayer.cpp
0x63 was treated as having a 1-byte parameter but it actually has no parameters. This could advance the file position to a command parameter rather than a command. This could trigger the `return` in the `default` case. Therefore, a VGM 1.01 file that uses the YM2612 or the YM2151 (instead of the YM2413) could be rendered as silence because the YM2612/YM2151 clock rate could remain set to 0.
To fix this, we can just remove the cases for commands 0x50, 0x61, and 0x63 because the `default` case handles them just fine.
=> VGMPlayer::ParseFileForFMClocks: handle command 0x63 correctly

audemutest.c
Following up on our chat on IRC about audemutest. Thanks for the help!
audemutest hadn't been updated with a working resampler mode since the breaking change in 77c34eb8cc96eaf44f8f4125a89356f6d5ffc76a that made `0xFF` invalid.
Updated and working value for mode taken from here: https://github.com/ValleyBell/libvgm/blob/master/player/vgmplayer.cpp#L1599
This test worked on an out-of-date fork of libvgm, so I tested every commit since then until it broke again.
Commit:
- fix resampleMode in Resmpl_SetVals() for breaking change in 77c34eb8cc96eaf44f8f4125a89356f6d5ffc76a
=> audemutest: Update broken Resampler mode

CMakeLists.txt, _stdbool.h, audio/AudioStream.c, common_def.h, emu/cores/gb.c, emu/cores/mikey.c, emu/cores/nes_apu.c, emu/cores/nes_defs.h, emu/cores/nesintf.c, emu/cores/np_nes_apu.c, emu/cores/np_nes_dmc.c, emu/cores/np_nes_fds.c, emu/cores/ymf271.c, libVgmTest.vcxproj, libVgmTest.vcxproj.filters
also change it so it will import some known system headers where possible, such as GNU C / clang, or MSVC 2015+
This should fix compilation on Fedora 42 beta, where bool is apparently a native type even in the default C standard. Rename the substitute header, or else `<stdbool.h>` will just wrap around on itself.
=> rename stdbool substitute
